### ISSUE TITLE
The "Now Playing" screen isn't updated when the music is from iCloud Music Library

### ISSUE THREAD

**Issue by igor-makarov** [antrancs/maeve#12]
Steps to reproduce:
1. Enable iCloud Music Library.
2. Add an album that Apple Music doesn't recognize.
3. Play it in Maeve.

Expected result: "Now Playing" gets updated with current music.  
Actual result: "Now Playing" stays with whatever was playing before. If nothing was playing, the bottom "Now Playing" view is not visible at all. Playlist and song position get updated correctly but the title and image are not.

**Comment by igor-makarov** [comment]
My guess is something to do with it not having album artwork?

**Comment by antrancs** [comment]
Can you give me the link to the album that does not have an artwork as an example?

And I'm not sure I understand the steps to reproduce, let me clarify it:
1. Play an album NOT from the Library.
2. Then add a different album to the library.
3. Play the album I just added

The bug is the title & image in the Now Playing bar is not updated.

Is that correct?

**Comment by antrancs** [comment]
Okay, thanks for the details. I'll look into it.

**Comment by igor-makarov** [comment]
I've just played an album that's from my iCloud Music Library and the bug hasn't occured!  
Did you do any work on this or did the issue go away because of Apple?

**Comment by antrancs** [comment]
Apple has fixed it. It wasn't supported at first. But now it's working fine 😁

Still waiting for the Radio Station support though.

**Comment by igor-makarov** [comment]
Awesome! Very nice.
