### ISSUE TITLE
Freeze site, when try search music

### ISSUE THREAD

**Issue by ihusky02** [antrancs/maeve#3]
Hi, everytime when I try search "Dark Sanctuary" or any other in  shop (not local) site sudennly freeze and I can`t do anything.

I use Linux Mint 19.1 64 bit and latest Google Chrome

**Comment by antrancs** [comment]
Did it freeze when you typed the search text in the search textbox or you clicked on the "View All" link?

**Comment by ihusky02** [comment]
> > When I click view all results (songs) , when I wrote a artist
> 
> Ah, yes, that's a bug when you try to View All in the search results. I will fix it

thanks, heh in near future it will be better better than iTunes. If you will add a new functions and repair issues XD

**Comment by antrancs** [comment]
@ihusky02 Hi, the new build should fix the issue. Sorry I was a bit delayed as I've been busy working on the Charts page. Now it should be okay 😄. Let me know if it's working fine for you as well.

**Comment by ihusky02** [comment]
> @ihusky02 Hi, the new build should fix the issue. Sorry I was a bit delayed as I've been busy working on the Charts page. Now it should be okay . Let me know if it's working fine for you as well.

Great :) I heard that you want release, your own app for Windows, Mac OS X and (I have a hope)  for Linux  (I hate windows)  but can you add function to add local files to your app?

**Comment by antrancs** [comment]
Hi, my current plan is to make Maeve a Progressive Web App. It is basically a web wrapper, but looks like an app. You can install a PWA (add it to your home screen) on Linux, Mac or Windows. It takes less effort to make Maeve a PWA as I just need to add a couple of things to the existing codebase.

Regarding your suggestion, it's a nice idea but it requires making a separate desktop version for Maeve because web applications cannot access local files or things like that.

So, I'll add it to my roadmap and try to implement it when time permits.
