### ISSUE TITLE
Not playing music, just keeps loading.

### ISSUE THREAD

**Issue by mattharo** [antrancs/maeve#34]

**Comment by antrancs** [comment]
Hi, can you give more details about your environment (OS, browsers) and steps to reproduce (play album/playlist/song....)?
Thanks

**Comment by mattharo** [comment]
I am running this program on Chrome OS. I attempted to log out and then back in, but this does not resolve the issue.

**Comment by DeadmanIQ445** [comment]
Same here using Chrome 72.0.3626.119 (Official Build) (64-bit) on Windows 10 1809. 
![image](https://user-images.githubusercontent.com/35527371/53588372-dae73300-3b9d-11e9-916a-a7c3ddd85df5.png) 

But I have to say that musish doesn't play anything as well. However, Deezer works fine.

**Comment by antrancs** [comment]
@mattharo, @DeadmanIQ445 : Thanks a lot for the info. I've tried playing a library album using Chrome (on MacOS) and it's working for me. I don't have my Windows machine with me right now so I can't test it on Windows. Will be home this weekend so I can test around on Windows environment.

But glad it works for @DeadmanIQ445 now. Sometimes, I've bumped into this before and turns out it's due to the CORS error from Apple server, which prevents the song from being downloaded from other domains. But it only happens to a couple of songs.

In the future, if you run into this error, could you please help right click and choose "Inspect" and see which error message is shown in the Console tab. That will help me investigate the issue.

Thanks.

**Comment by mattharo** [comment]
Thank you for the feedback! I was able to play music when logging out then back out.
![screenshot 2019-03-01 at 10 55 53 am](https://user-images.githubusercontent.com/48073208/53649711-c4c68a80-3c10-11e9-8f68-cd4f52a1c6eb.png)
