### ISSUE TITLE
It would be great if all of my songs would show in my playlist. Only 100 songs are showing at the moment.

### ISSUE THREAD

**Issue by mattharo** [antrancs/maeve#36]

**Comment by antrancs** [comment]
Hi, the new build should fix the issue. Now all your songs should be shown. Let me know if it's working fine for you as well.

**Comment by shawnc722** [comment]
Hi antrancs, this issue seems to have changed to 300 songs. In the library->songs menu, scrolling down will load more songs but only three times. Would it be possible to show all songs at once, similar to how itunes does?
Thanks for making such an awesome player, btw.

**Comment by antrancs** [comment]
@shawnc722 : Thanks, glad you like it 😄. Regarding the song library page, yes the limit is 300 songs at the moment because one can have thousands of songs which will impact the scrolling performance if I show them all.

I plan to work on showing all songs while maintaining smooth scrolling. But for now, I have to set the limit for it. I'll try to implement that soon. So stay tuned 🙌🏼
